name: tekartik_io_auth_utils
description: helper for google auth for io app
version: 0.2.0
homepage: https://github.com/tekartik/io_auth_utils.dart
author: alex <alex@tekartik.com>

environment:
  sdk: '>=2.0.0-dev.63 <3.0.0'

dependencies:
  googleapis_auth: any
  fs_shim: any
  tekartik_io_utils:
    git:
      url: git://github.com/tekartik/io_utils.dart
      ref: dart2
    version: '>=0.5.1'
dev_dependencies:
  test: ">=1.0.0"
  dev_test: any
  googleapis: any
