name: tekartik_io_auth_utils
description: helper for google auth for io app
version: 0.1.0
homepage: https://github.com/tekartik/io_auth_utils.dart
author: alex <alex@tekartik.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  googleapis_auth: any
  fs_shim: any
  tekartik_io_utils:
    git: git://github.com/tekartik/io_utils.dart

dev_dependencies:
  test: ">=0.12.24"
  dev_test: any
  googleapis: any
